<?php
define('ADMIN_RAIZ', '../');
require_once __DIR__ . '/../Controlador/verificar_admin.php';
require_once __DIR__ . '/../Controlador/conexion.php';
require_once __DIR__ . '/../Modelo/funciones_productos.php';
$filtros=['categoria'=>$_GET['categoria']??'','marca'=>$_GET['marca']??'','busqueda'=>trim($_GET['busqueda']??''),'precio_min'=>$_GET['precio_min']??'','precio_max'=>$_GET['precio_max']??'','disponible'=>$_GET['disponible']??'','orden'=>$_GET['orden']??'nombre_asc'];
$categorias=obtenerCategorias($pdo); $marcas=obtenerMarcas($pdo); $productos=obtenerProductos($pdo,$filtros);
?><!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Productos | Acero Gym</title><link rel="stylesheet" href="../index.css"></head><body>
<header class="header is-scrolled"><div class="container header__row"><a href="../index.php" class="logo"><span class="logo__mark">A</span><span class="logo__text">ACERO<span class="logo__sub">GYM</span></span></a><a href="producto_form.php" class="btn btn--solid">+ Agregar producto</a><a href="../productos.php" class="btn btn--ghost">Tienda pública</a></div></header>
<section class="section page-section"><div class="container"><p class="eyebrow"><span class="eyebrow__dash"></span>Administración</p><h1 class="h2">Gestión de productos</h1>
<form method="get" class="shop-filters"><input name="busqueda" placeholder="Buscar..." value="<?= htmlspecialchars($filtros['busqueda']) ?>"><select name="categoria"><option value="">Todas las categorías</option><?php foreach($categorias as $c): ?><option value="<?= $c['id_categoria'] ?>" <?= (string)$filtros['categoria']===(string)$c['id_categoria']?'selected':'' ?>><?= htmlspecialchars($c['nombre_categoria']) ?></option><?php endforeach; ?></select><select name="marca"><option value="">Todas las marcas</option><?php foreach($marcas as $m): ?><option value="<?= $m['id_Marca'] ?>" <?= (string)$filtros['marca']===(string)$m['id_Marca']?'selected':'' ?>><?= htmlspecialchars($m['nombre']) ?></option><?php endforeach; ?></select><button class="btn btn--solid">Filtrar</button></form>
<p><?= count($productos) ?> producto(s)</p><div class="shop-grid">
<?php foreach($productos as $p): $img = resolverImagenProducto($p); ?><article class="shop-card"><div class="shop-card__image"><?php if($img): ?><img src="../<?= htmlspecialchars($img) ?>" alt=""><?php else: ?><div class="shop-no-image">ACERO</div><?php endif; ?></div><div class="shop-card__body"><span class="shop-card__category"><?= htmlspecialchars($p['nombre_categoria']??'Sin categoría') ?></span><h3><?= htmlspecialchars($p['nombre']) ?></h3><p><?= htmlspecialchars($p['nombre_marca']??'Sin marca') ?></p><?php if(!empty($p['descripcion'])): ?><p class="shop-card__desc"><?= htmlspecialchars($p['descripcion']) ?></p><?php endif; ?><p>Stock: <strong><?= (int)$p['stock_actual'] ?></strong></p><div class="shop-card__bottom"><strong>$<?= number_format((float)$p['precio_venta'],0,',','.') ?></strong><span><a class="btn btn--outline" href="producto_form.php?id=<?= (int)$p['id_producto'] ?>">Editar</a> <form style="display:inline" method="post" action="../Controlador/eliminar_producto.php" onsubmit="return confirm('¿Eliminar este producto?')"><input type="hidden" name="id_producto" value="<?= (int)$p['id_producto'] ?>"><button class="btn btn--outline" type="submit">Eliminar</button></form></span></div></div></article><?php endforeach; ?></div></div></section></body></html>
